### ISSUE TITLE
Paksa pengguna client harus menggunakan chrome dan harus versi terbaru

### ISSUE THREAD

**Issue by reacto11mecha** [reacto11mecha/enpitsu#59]
Gunakan [UAParser.js](https://uaparser.js.org/) supaya para pengguna hape android menggunakan browser chrome versi paling terbaru. Jika tidak maka akan menampilkan tampilan yang memaksa mereka menggunakan chrome. Tetapi jika sudah menggunakan chrome, wajib menggunakan versi terbaru.

**Comment by reacto11mecha** [comment]
Lain kali teliti, gara gara satu baris debug hampir 2 jam sendiri sama client

https://github.com/reacto11mecha/enpitsu/commit/990f0174ce02d7bb31311cbd05285e6502914380

**Comment by manoedinata** [comment]
Kenapa force chrome ?

**Comment by OverhandBook79** [comment]
> Kenapa force chrome ?

Mungkin takut ada yg make ekstensi browser?

**Comment by manoedinata** [comment]
Menarik. Yang paling bener exambro disambungkan ke Enpitsu sih, hehee
